version: '3.8'

services:
  database:
    tty: true
    restart: unless-stopped
    image: postgres:12
    container_name: ${POSTGRES_CONTAINER_NAME}
    volumes:
      - db_volume:/var/lib/postgresql/data
    networks:
      - db_network
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_EXTERNAL_PORT}:${POSTGRES_INTERNAL_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 120s

volumes:
  db_volume:
    name: ${POSTGRES_VOLUME_NAME}
    external: false

networks:
  db_network:
    name: ${POSTGRES_NETWORK_NAME}
    external: false
